sonar.organization=govuk-once
sonar.projectKey=govuk-once_events-aggregator

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src, cdk

# exclude CDK infrastructure code from coverage
sonar.coverage.exclusions=cdk/**

# enforce quality gates (remove #)
# sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=coverage/lcov.info
