name: Build & Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true
        default: 'dev'
      github-environment:
        description: 'Environment in github'
        type: string
        required: false
        default: 'dev'
      aws_region:
        description: 'AWS region'
        type: string
        required: false
        default: 'eu-west-2'
      VERSION:
        description: 'Semantic version being deployed'
        type: string
        default: '0.0.0'
        required: true
    secrets:
      DEPLOYMENT_ROLE:
        description: 'AWS deployment role to assume'
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - development
          - staging
      aws_region:
        description: 'AWS region'
        required: false
        default: 'eu-west-2'
        type: string
      VERSION:
        description: 'Semantic version being deployed'
        type: string
        default: '0.0.0'
        required: true
    secrets:
      DEPLOYMENT_ROLE:
        description: 'AWS deployment role to assume'
        required: true

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-environment }}
    env:
      FLEX_ACCOUNT_ID: ${{ vars.FLEX_ACCOUNT_ID }}
      FLEX_EXTERNAL_ID: ${{ vars.FLEX_EXTERNAL_ID }}
      ENVIRONMENT: ${{ inputs.environment }}
      VERSION: ${{ inputs.VERSION }}
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      actions: write
      statuses: write
    concurrency:
      group: deploy-${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v5.0

      - name: Get PNPM Version
        id: pnpm-version
        run: echo "pnpm_version=$(jq -r '.packageManager' package.json)" >> $GITHUB_OUTPUT

      - name: Install pnpm
        run: npm install -g ${{ steps.pnpm-version.outputs.pnpm_version }}

      - name: setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v4.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@6782cb1b6df5d32e9354c1e6d6da4f956c0d61c4 # v5.1.1
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          aws-region: ${{ inputs.aws_region }}
          output-env-credentials: true

      - name: Pre-deploy SSM parameter setup
        run: pnpm run cdk:predeploy
        env:
          SSM_PARAMETERS_TO_UPDATE: ${{ vars.SSM_PARAMETERS_TO_UPDATE }}

      - name: Build Application
        run: pnpm run build

      - name: Deploy to Environment
        run: pnpm run deploy:dev
