name: Pull Request

on:
  push:
    branches:
      - main

jobs:
  QualityChecks:
    name: 🧪  Quality Checks
    # needs: GetDependencies
    secrets: inherit
    uses: ./.github/workflows/_quality_checks.yml

  DeployToDev:
    name: 🛠️  Deploy To Dev Env
    needs: QualityChecks
    secrets: inherit
    uses: ./.github/workflows/_build_deploy.yml
    with:
      environment: development

  SeedDev:
    name: Seed dev data
    needs: DeployToDev
    uses: ./.github/workflows/_seed_data.yml
    with:
      environment-name: development
      service-name: dynamotable
      table-name: development-dynamotable-sourceStore
    secrets:
      DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}

  # DeployToStaging:
  #   name: 🛠️  Deploy To Staging Env
  #   needs: QualityChecks
  #   secrets: inherit
  #   uses: ./.github/workflows/_build_deploy.yaml
  #   with:
  #     environment: staging
  #     aws_account: 33333333333
