name: Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  USER: pr-${{ github.event.pull_request.number }}

jobs:
  ValidatePR:
    name: Validate PR
    uses: ./.github/workflows/_validate_pr.yml

  QualityChecks:
    name: 🧪  Quality Checks
    needs: ValidatePR
    # needs: GetDependencies
    secrets: inherit
    uses: ./.github/workflows/_quality_checks.yml

  DeployToDev:
    name: 🛠️ Deploy To Dev Env
    needs: QualityChecks
    secrets: inherit
    uses: ./.github/workflows/_build_deploy.yml
    with:
      environment: development

  SeedDev:
    name: Seed dev data
    needs: DeployToDev
    uses: ./.github/workflows/_seed_data.yml
    with:
      environment-name: development
      service-name: dynamotable
      table-name: runner-dynamotable-sourceStore
    secrets:
      DEPLOYMENT_ROLE: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
